# Generated by Django 3.0.4 on 2020-03-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('time', models.TextField(choices=[['morning', 'morning'], ['afternoon', 'afternoon']])),
            ],
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Chore')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Student')),
            ],
        ),
    ]
