# Generated by Django 3.0.4 on 2020-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chore_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chore_one_pref',
            field=models.TextField(choices=[['Chore Captain', 'Chore Captain'], ['Pre-lunch Bathroom Inspection', 'Pre-lunch Bathroom Inspection'], ['Lunch Set-up', 'Lunch Set-up'], ['Lunch Clean-up', 'Lunch Clean-up'], ['Bathroom Cleaner 1', 'Bathroom Cleaner 1'], ['Bathroom Cleaner 2', 'Bathroom Cleaner 2'], ['Classroom Clean and Inspection', 'Classroom Clean and Inspection'], ['End of Day Classroom Clean and Inspection', 'End of Day Classroom Clean and Inspection'], ['Hallway Sweep', 'Hallway Sweep'], ['Classroom Sweeper 1', 'Classroom Sweeper 1'], ['Classroom Sweeper 2', 'Classroom Sweeper 2'], ['End of Day Bathroom Clean and Inspection', 'End of Day Bathroom Clean and Inspection']]),
        ),
        migrations.AlterField(
            model_name='student',
            name='chore_three_pref',
            field=models.TextField(choices=[['Chore Captain', 'Chore Captain'], ['Pre-lunch Bathroom Inspection', 'Pre-lunch Bathroom Inspection'], ['Lunch Set-up', 'Lunch Set-up'], ['Lunch Clean-up', 'Lunch Clean-up'], ['Bathroom Cleaner 1', 'Bathroom Cleaner 1'], ['Bathroom Cleaner 2', 'Bathroom Cleaner 2'], ['Classroom Clean and Inspection', 'Classroom Clean and Inspection'], ['End of Day Classroom Clean and Inspection', 'End of Day Classroom Clean and Inspection'], ['Hallway Sweep', 'Hallway Sweep'], ['Classroom Sweeper 1', 'Classroom Sweeper 1'], ['Classroom Sweeper 2', 'Classroom Sweeper 2'], ['End of Day Bathroom Clean and Inspection', 'End of Day Bathroom Clean and Inspection']]),
        ),
        migrations.AlterField(
            model_name='student',
            name='chore_two_pref',
            field=models.TextField(choices=[['Chore Captain', 'Chore Captain'], ['Pre-lunch Bathroom Inspection', 'Pre-lunch Bathroom Inspection'], ['Lunch Set-up', 'Lunch Set-up'], ['Lunch Clean-up', 'Lunch Clean-up'], ['Bathroom Cleaner 1', 'Bathroom Cleaner 1'], ['Bathroom Cleaner 2', 'Bathroom Cleaner 2'], ['Classroom Clean and Inspection', 'Classroom Clean and Inspection'], ['End of Day Classroom Clean and Inspection', 'End of Day Classroom Clean and Inspection'], ['Hallway Sweep', 'Hallway Sweep'], ['Classroom Sweeper 1', 'Classroom Sweeper 1'], ['Classroom Sweeper 2', 'Classroom Sweeper 2'], ['End of Day Bathroom Clean and Inspection', 'End of Day Bathroom Clean and Inspection']]),
        ),
    ]
